export const CaseManagementCopy = {
  pageTitle: 'სააღსრულებლო წარმოება',
  notifications: 'შეტყობინებები',
  filtersTitle: 'ძებნა',
  filtersPanelExpand: 'გაშლა',
  filtersPanelCollapse: 'აკეცვა',
  filtersExpand: 'დამატებითი პარამეტრები',
  filtersCollapse: 'დამატებითის აკეცვა',
  participantSearchTitle: 'მონაწილის ძებნა',
  orgTypeLabel: 'ორგანიზაციის ტიპი',
  orgLabel: 'ორგანიზაცია',
  appRegNoLabel: 'განცხადების ნომერი',
  trTypeLabel: 'აღსრულების ტიპი',
  transferStatusLabel: 'გადარიცხვის სტატუსი',
  sourceLabel: 'შემოსვლის წყარო',
  regPeriodLabel: 'პერიოდი (რეგ. თარიღი)',
  statusPeriodLabel: 'პერიოდი (სტატუსის თარიღი)',
  participantTypeLabel: 'მონაწილის ტიპი',
  personalIdNumberLabel: 'პირადი ნომერი',
  legalIdentificationCodeLabel: 'საიდენტიფიკაციო კოდი',
  idNumberLabel: 'პირადი ნომერი / საიდენტ. კოდი',
  firstNameLabel: 'სახელი',
  lastNameLabel: 'გვარი',
  addressLabel: 'მისამართი',
  organizationNameLabel: 'დასახელება',
  enforcementSheetNoLabel: 'სააღსრულებლო ფურცლის ნომერი',
  paymentIdLabel: 'გადახდის იდენტიფიკატორი',
  cadastralCodeLabel: 'საკადასტრო კოდი',
  vehicleNoLabel: 'მანქანის სახელმწიფო ნომერი',
  postNoLabel: 'ფოსტის ნომერი',
  autoProcessLabel: 'ავტომატური პროცესები',
  updateByDateLabel: 'განახლების თარიღის მიხედვით',
  conditionalLabel: 'პირობითი განცხადება',
  immediateEnfLabel: 'დაუყოვნებლივი აღსრულება',
  searchButton: 'ძებნა',
  clearButton: 'X',
  emptyMessage: 'მონაცემები ვერ მოიძებნა',
  emptyNoProceedingsMessage:
    'თქვენი მონაწილეობით სააღსრულებო წარმოება არ მიმდინარეობს.',
  loadingMessage: 'იტვირთება...',
  listError: 'სააღსრულებლო წარმოების სიის წამოღება ვერ მოხერხდა.',
  previousPage: 'წინა',
  nextPage: 'შემდეგი',
  paginationFirst: '« პირველი',
  paginationLast: 'ბოლო »',
  paginationTotalRecords: '{count} ჩანაწერი',
  executorPrefix: 'აღმ.',
  creditor: 'კრედიტორი(ები)',
  debtor: 'მოვალე(ები)',
  listApplicationLine: 'განცხადება',
  listCaseNumberLabel: 'საქმის ნომერი',
  listRegistrationLine: 'საბოლოო რეგისტრაცია',
  listCreditorDebtorLine: 'კრედიტორი / მოვალე',
  listDebtLine: 'დავალიანება (კატეგორია)',
  openCaseA11yHint: 'სრული ინფორმაცია და გადახდა',
  detailTitle: 'სააღსრულებლო წარმოება',
  detailBack: 'უკან',
  detailMyGovSection: 'ინფორმაცია (My.gov.ge)',
  detailMyGovPlaceholder:
    'აქ გამოჩნდება სრული მონაცემები — როგორც My.gov.ge-ზეა გატანილი. ინტეგრაციის შემდეგ ჩაიტვირთება ავტომატურად.',
  detailDebtSection: 'დავალიანება და გადახდა',
  detailDebtPlaceholder:
    'დავალიანების დეტალები და გადახდის ბმული გამოჩნდება სერვისიდან მიღებული მონაცემების შემდეგ.',
  detailPayButton: 'გადახდა',
  detailPaySoonToast: 'გადახდის მოდული მიერთდება სერვისის მიხედვით.',
} as const;
