export const CaseManagementCopy = {
  pageTitle: 'საქმის წარმოება',
  notifications: 'შეტყობინებები',
  filtersTitle: 'ფილტრები',
  filtersExpand: 'ფილტრების ჩვენება',
  filtersCollapse: 'ფილტრების აკეცვა',
  orgTypeLabel: 'ორგანიზაციის ტიპი',
  orgLabel: 'ორგანიზაცია',
  appRegNoLabel: 'განცხადების ნომერი',
  trTypeLabel: 'აღსრულების ტიპი',
  transferStatusLabel: 'გადარიცხვის სტატუსი',
  sourceLabel: 'შემოსვლის წყარო',
  regPeriodLabel: 'პერიოდი (რეგ. თარიღი)',
  statusPeriodLabel: 'პერიოდი (სტატუსის თარიღი)',
  participantTypeLabel: 'მონაწილის ტიპი',
  idNumberLabel: 'პირადი ნომერი / საიდენტ. კოდი',
  firstNameLabel: 'სახელი',
  lastNameLabel: 'გვარი',
  addressLabel: 'მისამართი',
  organizationNameLabel: 'ორგანიზაცია (მონაწილე)',
  paymentIdLabel: 'გადახდის იდენტიფიკატორი',
  cadastralCodeLabel: 'საკადასტრო კოდი',
  vehicleNoLabel: 'მანქანის სახელმწიფო ნომერი',
  postNoLabel: 'ფოსტის ნომერი',
  autoProcessLabel: 'ავტომატური პროცესები',
  updateByDateLabel: 'განახლების თარიღის მიხედვით',
  conditionalLabel: 'პირობითი განცხადება',
  immediateEnfLabel: 'დაუყოვნებლივი აღსრულება',
  searchButton: 'ძებნა',
  clearButton: 'X',
  emptyMessage: 'მონაცემები ვერ მოიძებნა',
  loadingMessage: 'იტვირთება...',
  listError: 'საქმეების სიის წამოღება ვერ მოხერხდა.',
  previousPage: 'წინა',
  nextPage: 'შემდეგი',
  creditor: 'კრედიტორი(ები)',
  debtor: 'მოვალე(ები)',
} as const;
