export const DebtorRegistryCopy = {
  pageTitle: 'მოვალეთა რეესტრი',
  notifications: 'შეტყობინებები',
  filtersTitle: 'ფილტრები',
  filtersExpand: 'ფილტრების ჩვენება',
  filtersCollapse: 'ფილტრების აკეცვა',
  idNumberLabel: 'პირადი ნომერი / საიდენტ. კოდი',
  firstNameLabel: 'სახელი',
  lastNameLabel: 'გვარი',
  organizationLabel: 'ორგანიზაცია',
  periodLabel: 'პერიოდი',
  periodFromPlaceholder: 'დან (YYYY-MM-DD)',
  periodToPlaceholder: 'მდე (YYYY-MM-DD)',
  searchButton: 'ძებნა',
  clearButton: 'X',
  emptyMessage: 'მონაცემები ვერ მოიძებნა',
  loadingMessage: 'იტვირთება...',
  listError: 'განაცხადების სიის წამოღება ვერ მოხერხდა.',
  detailsTitlePrefix: 'მოვალეთა რეესტრი - განცხადება',
  detailsOpenHint: 'დეტალების გახსნა',
  statementAction: 'განცხადება',
  statementOpenError: 'განცხადების გახსნა ვერ მოხერხდა.',
  detailsClose: 'დახურვა',
  detailsEditableSection: 'განმცხადებელი',
  detailsReadonlySection: 'რეგისტრაცია',
  previousPage: 'წინა',
  nextPage: 'შემდეგი',
} as const;
