export const LoginCopy = {
  pageTitle: "ავტორიზაცია",
  usernamePlaceholder: "მომხმარებლის სახელი",
  passwordPlaceholder: "პაროლი",
  submit: "შესვლა",
  brandGeo: "აღსრულების ეროვნული ბიურო",
  brandEn: "NATIONAL BUREAU OF ENFORCEMENT",
  footerLeft:
    "© სსიპ „ციფრული მმართველობის სააგენტო“, 2026, ყველა უფლება დაცულია.",
  agencyName: "ციფრული მმართველობის სააგენტო",
  loginUnauthorized: "მომხმარებლის სახელი ან პაროლი არასწორია.",
  loginNetworkError: "ქსელში შეცდომა. სცადეთ თავიდან.",
  loginGenericError: "შესვლა ვერ მოხერხდა. სცადეთ თავიდან.",
  guestLink: "ავტორიზაციის გარეშე გაგრძელება",
  registrationLink: "რეგისტრაცია",
  registrationPageTitle: "რეგისტრაცია",
  registerTabPhysical: "ფიზიკური პირი",
  registerTabLegal: "იურიდიული პირი",
  registerPhysicalFirstName: "სახელი",
  registerPhysicalLastName: "გვარი",
  registerPhysicalPersonalId: "პირადი ნომერი",
  registerPhysicalEmail: "ელ-ფოსტა",
  registerPhysicalPhone: "ტელეფონი",
  registerPhysicalPassword: "პაროლი",
  registerPasswordConfirm: "გაიმეორეთ პაროლი",
  registerLegalCompanyName: "დასახელება",
  registerLegalIdentificationCode: "საიდენტიფიკაციო კოდი",
  registerLegalRepresentative: "წარმომადგენელი (სახელი, გვარი)",
  registerLegalEmail: "ელ-ფოსტა",
  registerLegalPhone: "ტელეფონი",
  registerLegalPassword: "პაროლი",
  registerSubmit: "რეგისტრაცია",
  registerBackA11yLabel: "უკან",
  sessionBootLoadingA11yLabel: "სესიის შემოწმება",
} as const;
